### ISSUE TITLE
Some ideas for packages

### ISSUE THREAD

**Issue by samcarter** [samcarter/PackageOfTheDay#1]
- [x] \input{insbox.tex}
- [x] avremu
- [x] spath3
- [x] https://www.ctan.org/pkg/adfsymbols
- [x] https://www.ctan.org/pkg/arara
- [ ] https://www.ctan.org/pkg/afterpackage
- [ ] https://github.com/marmotghost/tikz-3dtools
- [ ] https://github.com/marmotghost/tikz-bbox
- [x] bearwear
- [ ] https://www.ctan.org/pkg/braket
- [x] cookybooky
- [x] https://www.ctan.org/pkg/datetime2
- [x] download
- [x] nndraw
- [x] https://ctan.org/pkg/tikz-layers
- [x] https://ctan.org/pkg/tikz-swigs
- [x] texsurgery
- [x] https://www.ctan.org/pkg/cryst
- [ ] https://ctan.org/pkg/graph35
- [x] https://www.ctan.org/pkg/pfdicons
- [x] https://ctan.org/pkg/tikzbricks
- [x] https://ctan.org/pkg/aboensis
- [x] https://www.ctan.org/pkg/cancel
- [x] https://www.ctan.org/pkg/casiofont
- [x] https://www.ctan.org/pkg/changebar
- [x] https://www.ctan.org/pkg/chemplants

**Comment by marmotghost** [comment]
- [x] For 02/02: `tikzmarmots`. https://en.wikipedia.org/wiki/Marmot_Day 🐿️

**Comment by LucaPolese** [comment]
- [x]  What if for 31/12 or 01/01 we put: `folding`? So that you can print the new year calendar 😄.
Like on page 725 of the manual https://ctan.mirror.garr.it/mirrors/ctan/graphics/pgf/base/doc/pgfmanual.pdf.

**A little update:**
The following packages could be added if desired
- [x] `calxxxx-yyyy` package to produce a calendar with a more classic style https://www.ctan.org/pkg/calxxxx-yyyy or its alternatives `calxxxx` and  `kalendar` (the latter can be used to obtain a calendar in German)
- [x]  `china2e` package to produce Chinese calendar symbols of the old Chinese lunisolar calendar
- [ ] `zh-mod`  another package to produce Chinese calendar symbols, but *not* the lunisolar calendar! (e.g. https://www.overleaf.com/project/60cc5fcb30c4617e74646b40)

**Comment by samcarter** [comment]
@LucaPolese  Great idea! Thanks for your contribution!

**Comment by LucaPolese** [comment]
- [x]  @samcarter I had no idea this package existed, but maybe it would be useful to someone: `simpsons` 🤣 https://www.ctan.org/pkg/simpsons

**Comment by davidcarlisle** [comment]
- [x]  christmas day: xii
- [x]  shortest day: indentfirst
- [x]  longest day: longtable

**Comment by Plergux** [comment]
My five cents: 

- [x]  `make4ht` (my current obsession)
- [x]  `tikz-among-us` (impostors everywhere! :D)
- [x]  `SQLTeX` (I like anything "cross-platform" :p)
- [x]  `gamebook ` (nostaaaalgiaaaa)
- [x]  `knitting` (actual knitting, not R :p)
- [x]  `mwe` (so useful!)
- [x]  `PythonTeX` (again, for smushing together nice things)
- [x]  `fibnum` (obsessed)
- [x]  `filecontents` (also very useful)
- [x]  `duckuments` (you can never have too many ducks)
- [x]  `eCards` (usefulnessess!)
- [x]  `coffeestains` (top ten LaTeX packages ever)
- [x]  `cascover` (so much nostalgia! XD)
- [x]  `awesomebox` (with awesomefont)
- [x]  `acromemory` (more LaTeX gaming)
- [x]  `chickenize` (super adorable fun)
- [x]  `chroma` (not really a package, obsession + geek trip)
- [x]  `chronosys` (pretty!)
- [x]  `array` (super duper über useful)
- [x]  `archaic` (comes in handy surprisingly often)

**Comment by Skillmon** [comment]
I don't want to self-praise myself (and somehow a few of my fun-packages already ended up in this list of suggestions), but I'd like to suggest the `expkv` package family (as a single item in the list, no need to block four slots):

   * [x]   `expkv`, `*-def`, `*-cs`, `*-opt`

**Comment by niruvt** [comment]
- [x] [`datestamp`](https://ctan.org/pkg/datestamp)

**Comment by Skillmon** [comment]
- [x]  I've never used it (I didn't even skim over the manual yet) but the idea looks interesting: [`makeshape`](https://ctan.org/pkg/makeshape).

**Comment by Skillmon** [comment]
- [x] [`numerica`](https://ctan.org/pkg/numerica)

**Comment by Skillmon** [comment]
- [x] [`savetrees`](https://ctan.org/pkg/savetrees) (not because it looks great, but I didn't know it yet and think it can be of use for tight page requests)

**Comment by frougon** [comment]
I believe these haven't been presented yet:

- [x] `catchfile`
- [x] `ifoddpage`
- [x] `qrcode`
- [x] the `calligraphy` TikZ library.

I've used all of them, they are good packages!

**Comment by samcarter** [comment]
@frougon  Thanks a lot for your suggestion!

**Comment by koppor** [comment]
- [x] [microtype](https://ctan.org/pkg/microtype?lang=de), because it offers good typography automatically. "Optischer Randausgleich" und "Grauwertkorrektur". Open the user manual on page 3 with Acrobat Reader an you can see the differences when this package is loaded and when not.
- [x] [selnolig](https://ctan.org/pkg/selnolig?lang=de), because it offers correct usage of ligatures. A knowledge disappearing in busy times.
- [x] [authorarchive](https://ctan.org/pkg/authorarchive?lang=de), because it allows proper self-archiving for public conferences.
- [x] [intopdf](https://ctan.org/pkg/intopdf). I am not sure about this one. It was created based on a [discussion on tex.stackexchange](https://tex.stackexchange.com/q/418606/9075). I did not inspect `attachfile2`, but (all?) other alternatives.
- [x] [paralist](https://ctan.org/pkg/paralist?lang=de) - I use that since ages and think, it is worth being recommended
- [x] [refcheck](https://ctan.org/pkg/refcheck?lang=de)

**Comment by samcarter** [comment]
@koppor  Thanks for your suggestions!

**Comment by samcarter** [comment]
.... Thanks to everybody who contributed ideas!

**Comment by koppor** [comment]
@samcarter For new packages, we should open a new issue? Seeing pax today, I would really love to see https://ctan.org/pkg/newpax ^^

**Comment by samcarter** [comment]
@koppor  The packages of the day will soon complete their year. For the remaining couple of days, I already have packages planed.

I'm not yet sure how to proceed after that. I don't think I know enough packages to continue this much longer, but if there is interest from the community and enough ideas are contributed...

**Comment by CarLaTeX** [comment]
magicwatermark – An easy and flexible way to set watermarks
https://ctan.org/pkg/magicwatermark

**Comment by samcarter** [comment]
@all Please see https://github.com/samcarter/PackageOfTheDay/issues/11

**Comment by samcarter** [comment]
New suggestion thread at https://github.com/samcarter/PackageOfTheDay/issues/12
